### ISSUE TITLE
Welcome message crashing

### ISSUE THREAD

**Issue by obiwac** [fldardenne/DiscordSINFBot#61]
Log output:

```
TypeError: newMember.send is not a function
    at Object.execute (/DiscordSINFBot/src/events/guildMemberAdd.js:19:22)
    at Client.<anonymous> (/DiscordSINFBot/src/bot.js:64:44)
    at Client.emit (node:events:513:28)
    at module.exports [as GUILD_MEMBER_ADD] (/DiscordSINFBot/node_modules/discord.js/src/client/websocket/handlers/GUILD_MEMBER_ADD.js:16:14)
    at WebSocketManager.handlePacket (/DiscordSINFBot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:346:31)
    at WebSocketShard.onPacket (/DiscordSINFBot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:482:22)
    at WebSocketShard.onMessage (/DiscordSINFBot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:317:10)
    at WebSocket.onMessage (/DiscordSINFBot/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/DiscordSINFBot/node_modules/ws/lib/websocket.js:1178:20)
```

What was the intent of the welcome message functionality again?

**Comment by Emilevillette** [comment]
Fixed by #65
